### ISSUE TITLE
New Recommend 前端精读

### ISSUE THREAD

**Issue by ShaofeiZi** [online-books/moyu#26]
Name: 前端精读
Type: weekly
Link: https://github.com/ascoders/weekly
Remark: 前端精读周刊。帮你理解最前沿、实用的技术。

**Comment by xrkffgg** [comment]
猫哥很清闲啊

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/139848179-395b9f26-5663-4ecc-ad0b-adc4cb5e0b63.png)

已经有了哈~
